name: Discord Commit Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "ID length: ${#DISCORD_WEBHOOK_ID}"
          echo "TOKEN length: ${#DISCORD_WEBHOOK_TOKEN}"
        env:
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

      - name: Discord Commit Webhook
        uses: mrrobotdotapp/classic-discord-webhook@v2.0.1
        with:
          id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: GitHub Notifier
